services:
  catalog-service:
    build: ./catalog-service
    ports:
      - "5001:5001"
    networks:
      - tourist-net

  booking-service:
    build: ./booking-service
    ports:
      - "5002:5002"
    networks:
      - tourist-net

  payment-service:
    build: ./payment-service
    ports:
      - "5003:5003"
    networks:
      - tourist-net

 # НОВЫЙ СЕРВИС - ОРКЕСТРАТОР
  integration-service:
    build: ./integration-service
    ports:
      - "5000:5000"
    networks:
      - tourist-net
    depends_on:
      - catalog-service
      - booking-service
      - payment-service

networks:
  tourist-net:
    driver: bridge

    